# Generated by Django 3.2.6 on 2021-08-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('gender', models.CharField(max_length=15, verbose_name='Gender Customer')),
                ('company', models.CharField(max_length=100, verbose_name='Company')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('longitude', models.DecimalField(decimal_places=13, max_digits=20, verbose_name='Longitude')),
                ('latitude', models.DecimalField(decimal_places=13, max_digits=20, verbose_name='Longitude')),
            ],
            options={
                'db_table': 'oowlish_customers',
            },
        ),
    ]
